### PR TITLE
Tooltip: Sticky position and support for dynamic content (e.g. via React's `createPortal`)

### PR DESCRIPTION
**Pull request by rokotyan**
This PR will add support for sticky tooltip positioning:

https://github.com/f5/unovis/assets/755708/67e5b7f6-6746-4c7d-8a4b-d50a1c048b01

https://github.com/f5/unovis/assets/755708/b28e350d-315d-4754-9074-5b988f6e5261

### CODE REVIEW

**Comment by rokotyan** [comment]
@reb-dev  I think this is ready for review, but I'm having troubles finding time to update the docs to tell about these new features. If you think that either you or @lee00678 can do it, I would really appreciate it.

**Comment by reb-dev** [comment]
@rokotyan Nice feature! I will add the docs within the next couple days.

**Review by reb-dev — CHANGES_REQUESTED** [review]
@rokotyan When testing I noticed inconsistent behavior with crosshair when `followCursor` is `false`. The place where tooltip is hoverable seems to be random, and it sometimes follows the cursor even when crosshair isn't active.
 
It is difficult to showcase with a recording but here is an example of what I mean:


https://github.com/f5/unovis/assets/52078477/22130109-e22d-4dcf-a672-b64bda6f575d



I'm wondering if we can rework the logic so crosshair's tooltip can support this feature, or if we should automatically disable it?

**Comment by rokotyan** [comment]
@reb-dev You're right, I haven't tested this use case, thanks for your attention to detail! I think Crosshair doesn't need a hoverable tooltip, so we can safely disable it. I'll update the PR.

**Review by reb-dev — DISMISSED** [review]

**Comment by reb-dev** [comment]
I made some changes to the Tooltip doc page and added the new info in the recent commit.

@lee00678 can you review? Approval needs to be from someone besides the last pusher.

**Comment by lee00678** [comment]
@reb-dev looks good. Tested the dev examples and docs, both working as expected.

**Review by lee00678 — DISMISSED** [review]

**Comment by rokotyan** [comment]
Adding support for custom class names which is needed when using `createPortal` with multiple tooltips. Planning to finish this today.

**Comment by rokotyan** [comment]
@reb-dev @lee00678 Pushed a few more commits. Ready for review again.

**Comment by rokotyan** [comment]
New in the docs
image

image

image

**Review by reb-dev — APPROVED** [review]

**Comment by rokotyan** [comment]
Rebased from `main`

**Review by lee00678 — APPROVED** [review]

**Pull request merged**
