### PR TITLE
Solid Integration

### PR DESCRIPTION
**Pull request by rokotyan**
A clone of https://github.com/f5/unovis/pull/422, but rebased from `main` instead of merging. Let's see if the build passes.

### CODE REVIEW

**Comment by rokotyan** [comment]
There is one more problem with the build I've found. All Unovis libraries preserve the source directory structure in the dist, making it possible to import components individually, like `import { VisAnnotations } from '@unovis/react/components/area'`:
image

The Solid build doesn't have that, and it seems to be bundling all of `@unovis/ts` plus its dependencies. This will have a negative effect on the final bundle size of the apps that use `@unovis/solid`.
image

I think you can take a look at the `vite.config.ts` from `packages/vue` and use it as an example of the build configuration.

**Comment by lee00678** [comment]
> @hngngn @lee00678
> 
> I was able to make the solid build work, but the website build is failing because it can't find the examples for some reason. If you can take a look into this, it would be great. image

Yea, this happened to me during my test a couple of days ago as well. (https://github.com/f5/unovis/pull/475#issuecomment-2435549646) Seems to be this is caused by solid, so we may need some insights from @hngngn

**Comment by hngngn** [comment]
Sorry for the late reply—I've been pretty busy lately. I'll look into the issue and report back ASAP.

**Comment by hngngn** [comment]
I've already pushed a fix for both problems you're facing. Can you test it? @rokotyan @lee00678

**Comment by hngngn** [comment]
I've pushed a fix. Could you test it?

**Comment by lee00678** [comment]
@rokotyan do you mind pushing the latest fix so I can do a last round of testing before merging?

**Comment by rokotyan** [comment]
@lee00678 Done. Amended the main commit and did a force push.

**Comment by lee00678** [comment]
> I think you can take a look at the `vite.config.ts` from `packages/vue` and use it as an example of the build configuration.

This looks good!

**Comment by lee00678** [comment]
@hngngn Thanks for this contribution! This will be released in 1.5.0.

**Review by lee00678 — APPROVED** [review]

**Pull request merged**
