### PR TITLE
Dev | Examples | Donut chart: Component name fix while launching stac…

### PR DESCRIPTION
**Pull request by lucky-9**
When we open https://unovis.dev/gallery/view?collection=Circular%20Charts&title=Basic%20Donut%20Chart for Angular Framework, The stackblitz is not rendering the component. 
Screenshot 2024-07-25 at 5 18 43 PM

<br>

**This PR will fix this issue.**

### CODE REVIEW

**Comment by lucky-9** [comment]
I have hereby read the F5 CLA and agree to its terms

**Comment by lucky-9** [comment]
recheck

**Comment by lucky-9** [comment]
> **CLA Assistant Lite bot:** 🎉 Thank you for your contribution. It appears you have not yet signed the F5 Contributor License Agreement (CLA), which is required for your changes to be incorporated into an F5 project. Please kindly read the [F5 CLA](https://github.com/f5/.github/blob/main/CLA/cla-markdown.md) and comment the following to agree:
> 
> I have hereby read the F5 CLA and agree to its terms
> 
> **Pavan Kalyan BATTU** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

**recheck**

**Comment by lucky-9** [comment]
I have hereby read the F5 CLA and agree to its terms

**Comment by lee00678** [comment]
@lucky-9 nice catch! Thanks for the fix.

**Comment by lucky-9** [comment]
> or CLA so I can merge this i

@lee00678  I am not understanding how to finish the CLA, can you please explain?

**Comment by lucky-9** [comment]
recheck

**Comment by rokotyan** [comment]
@lucky-9 You probably need to set your email in git settings locally and redo the commit. It looks like GitHub was not able to identify your account:
image

**Comment by lucky-9** [comment]
@rokotyan @lee00678  Done. Please review and merge the code. Thank you

**Review by lee00678 — APPROVED** [review]

**Pull request merged**
