### PR TITLE
Fixing library import errors when used with Angular

### PR DESCRIPTION
**Pull request by rokotyan**
This PR fixes various compilation errors when the library is imported into Angular.

Also the installation instructions now have a note about enabling `allowSyntheticDefaultImports` in `tsconfig.json` 
image

### CODE REVIEW

**Review by reb-dev — COMMENTED** [review]
@rokotyan After running a clean install I see new `svelte-check` errors. Is it the case on your end too?
Screen Shot 2022-12-21 at 2 18 33 PM

**Comment by rokotyan** [comment]
@reb-dev I've pushed a fix for that using a force push but forgot to tell you. Can you please pull the latest version of the branch and try again?

**Review by reb-dev — APPROVED** [review]
@rokotyan Can confirm that the svelte-check errors are resolved. Approved!

**Comment by rokotyan** [comment]
@reb-dev Thanks!

**Pull request merged**
