### PR TITLE
feat: Solid support 

### PR DESCRIPTION
**Pull request by hngngn**
This PR adds SolidJS support to Unovis, expanding framework compatibility.

### CODE REVIEW

**Comment by hngngn** [comment]
I have hereby read the F5 CLA and agree to its terms

**Comment by hngngn** [comment]
recheck

**Comment by lee00678** [comment]
Hi @hngngn, thanks for this great contribution! We will review and get back to you soon!

**Comment by gabor-boros** [comment]
@lee00678 Do you have any update here?

**Comment by rokotyan** [comment]
@lee00678 I've tried it on my end, works like a charm. I would try to merge it asap and release 1.5.

Thanks for such a great contribution @hngngn! It's a shame it's taking us so long to review.

**Comment by lee00678** [comment]
@hngngn Thanks again for the great contribution and sorry for the delay.

**Review by lee00678 — APPROVED** [review]

**Comment by lee00678** [comment]
@hngngn can you please do a rebase from `main`? Once all the check get passed, I will merge it in.

**Comment by hngngn** [comment]
Hi, I've rebased from main and all the tests have passed. Could you please check again?

**Comment by lee00678** [comment]
Merged vis https://github.com/f5/unovis/pull/469

**Pull request closed without merging**
