### PR TITLE
Shared | Vue: Fix `Scatter Plot with Varied Shape` gallery demo

### PR DESCRIPTION
**Pull request by 50rayn**
* update dependencies in `/packages/vue`
* squash some little eslint warnings
* fix vite warning
* move `.eslintrc.cjs` to `eslint.config.js` since it is depracated in ESLint v9

I just observed that [Scatter Plot with Varied Shape](https://unovis.dev/gallery/view?collection=Scatter%20Plots&title=Scatter%20Plot%20with%20Varied%20Shape) example doesn't show anything on graph. So, this PR fixes this issue.

Besides the issue, were upgraded some Vue dependencies.

### CODE REVIEW

**Comment by lee00678** [comment]
@50rayn Thanks for the contribution. The Vue version seems to be loading for me in Stackblitz. Do you see any specific error messages?

**Comment by 50rayn** [comment]
The demo link for [Scatter Plot with Varied Shape](https://unovis.dev/gallery/view) is not working.

**Comment by 50rayn** [comment]
2024-11-22 at 21 13 29@2x

I don't see on:
* Firefox Version 132.0.2 (64-bit)
* Safari Version 18.1 (20619.2.8.11.10)

But on Chrome, it works fine.

**Comment by lee00678** [comment]
> In Safari and Firefox, `new Date ('Mar-2024')` gives `Invalid Date`.

I see, thanks for pointing this out. I just ran your PR, I think don't think fixes the issue. ```+(new Date(`${d.date}-01`))``` renders to `Jul-2023-01`, still an invalid expression for Safari.

**Comment by 50rayn** [comment]
Sorry, @lee00678, for my first submitted changes.
Just concatenated at the beginning of the first day of the month. Seems now works.
Personally, I see no reason to over-engineer this gallery item, in addition, we have a "constant" list of data for visualising. So, we obtain a clean and clear code example.
Hope, latest changes are ok.

**Comment by lee00678** [comment]
> Sorry, @lee00678, for my first submitted changes. Just concatenated at the beginning of the first day of the month. Seems now works. Personally, I see no reason to over-engineer this gallery item, in addition, we have a "constant" list of data for visualising. So, we obtain a clean and clear code example. Hope, latest changes are ok.

Yea, what you have now seems to be a good fix! Thanks.

**Review by lee00678 — APPROVED** [review]

**Pull request merged**
