### PR TITLE
Website: Fixed a  bug seen on https://unovis.dev/docs/xy-charts/Group…

### PR DESCRIPTION
**Pull request by nharrisanalyst**
Website: Fixed a  bug seen on https://unovis.dev/docs/xy-charts/GroupedBar/#orientation

The orientation on the selector does not match the visualization and makes a little bug that is fixed in this pull request 

image

### CODE REVIEW

**Comment by nharrisanalyst** [comment]
recheck

**Comment by lee00678** [comment]
@nharrisanalyst Thanks for the fix.

**Comment by nharrisanalyst** [comment]
I have hereby read the F5 CLA and agree to its terms

**Comment by nharrisanalyst** [comment]
recheck

**Review by lee00678 — APPROVED** [review]

**Comment by rokotyan** [comment]
Thanks for the fix @nharrisanalyst!

**Pull request merged**
