### PR TITLE
Component | Graph: Layout recalculation and persistency fix

### PR DESCRIPTION
**Pull request by rokotyan**
This PR fixes layout problems reported in #393:
- `fixNodePositionAfterSimulation` not working correctly in Force Layout
- Layout update when dynamically switching between different layouts

### CODE REVIEW

**Review by reb-dev — COMMENTED** [review]
@rokotyan I made a demo example to test this, I'm getting strange behavior if any panning/zooming occurs. Should we reset the transform on layout change as well?

https://github.com/f5/unovis/assets/52078477/837f3859-9b98-4335-a71c-40b6c0d22241

**Comment by lee00678** [comment]
@rokotyan I tried to modify one of the gallery example to test this. It seems once the layout changed, the chart no longer fit in the view window. 

https://github.com/f5/unovis/assets/5026041/ed9996d8-4f02-4e21-b32b-452c319b1a6b

**Comment by rokotyan** [comment]
@reb-dev @lee00678 Thanks for testing this! I didn't see such behavior in my environment, let me take another look.

**Comment by rokotyan** [comment]
@reb-dev Can you please push your example to the branch?

**Comment by rokotyan** [comment]
Thanks @reb-dev

My latest commits should take care of that and also fix https://github.com/f5/unovis/issues/393

**Comment by reb-dev** [comment]
@rokotyan Testing it again I'm discovering inconsistent behavior with `fixNodePositionAfterSimulation`.

Currently if you dynamically add data to the graph when it is set to `true`, the layout doesn't rearrange. When `false`, it does. However if you switch to `force` layout type from a different layout with `fixNodePositionAfterSimulation` set to `true`, the layout still rearranges on data updates.

Also could you clarify what the expected behavior is for this property?

**Comment by rokotyan** [comment]
@reb-dev You're right, something wrong is happening when changing the layout. Thanks for catching this, I'll investigate

**Comment by rokotyan** [comment]
@reb-dev Found the problem and fixed, see the last two commits. Thanks again for testing this thoroughly.

**Review by reb-dev — APPROVED** [review]
Thanks for the updates @rokotyan, looks good to me!

**Pull request merged**
