### PR TITLE
Website | Add new composite chart section and dual axis chart

### PR DESCRIPTION
**Pull request by lee00678**
- Adding a new section for composite chart. (With more examples coming)
- Add an example for dual axis chart. 

I ported over the one example in dev. Used generated data. Since it's pretty controversial in terms of whether/when people should use it, I figure we simply demo the way to do it, so users know it's a possibility.

dual-axis-chart

### CODE REVIEW

**Comment by rokotyan** [comment]
@lee00678 Great, thanks!

I think we should add to the description some brief text and references about pros and cons of using dual axis charts. Datawrapper has a great blog post on the subject: https://blog.datawrapper.de/dualaxis/

**Comment by rokotyan** [comment]
Also, I don't really like the style of the chart I created (I think there's too much red), but maybe it will help scare people away from using two-axis charts 😄

**Comment by lee00678** [comment]
> Also, I don't really like the style of the chart I created (I think there's too much red), but maybe it will help scare people away from using two-axis charts 😄

I'm happy to change it to bright orange &#x1F536; to make it more scary.

**Comment by rokotyan** [comment]
@lee00678 Yes, let's just flip them, thanks!

**Comment by lee00678** [comment]
> @lee00678 Great, thanks!
> 
> I think we should add to the description some brief text and references about pros and cons of using dual axis charts. Datawrapper has a great blog post on the subject: https://blog.datawrapper.de/dualaxis/

I added the following description, honestly I don't think there are much `pros` out there. Happy to edit. 

`This example shows how to create dual axis chart by overlapping two charts. Dual Axis chart maybe good at showing correlations, or compare two datasets with different measurement units. But we suggest using it with caution. Here are some good articles from [Datawrapper](https://blog.datawrapper.de/dualaxis/) and [Florish](https://flourish.studio/blog/dual-axis-charts/).`

**Comment by rokotyan** [comment]
@lee00678 Nice, I like it, thanks!

**Comment by lee00678** [comment]
Thanks for the reviews!

**Pull request merged**
