### PR TITLE
WIP fix resize observer bug

### PR DESCRIPTION
**Pull request by curran**
WIP towards #455

### CODE REVIEW

**Comment by curran** [comment]
Current status: uncovered the fact that multiple resize observers are set up on the same element.

image

It looks like the constructor is invoked twice for the exact same element.

**Comment by rokotyan** [comment]
> It looks like the constructor is invoked twice for the exact same element.

This is probably due to React rendering components twice in the dev [StrictMode](https://react.dev/reference/react/StrictMode#strictmode), which is a known behavior and usually not an issue — Unovis container components should disconnect the observer when destroyed.

**Comment by rokotyan** [comment]
I was able to reproduce this problem after setting "Show scroll bars" to "Always" in the macOS settings.

image

**Comment by rokotyan** [comment]
#463 should fix this

**Comment by 50rayn** [comment]
Is this PR still actual ?

**Comment by rokotyan** [comment]
@lee00678 I think we can close this one. I've fixed this issue in another PR.

**Pull request closed without merging**
