### PR TITLE
Vue: update `useForwardProps` function to latest implementation

### PR DESCRIPTION
**Pull request by sadeghbarati**
cc: @zernonia 🙌

### CODE REVIEW

**Comment by sadeghbarati** [comment]
I have hereby read the F5 CLA and agree to its terms

**Comment by rokotyan** [comment]
@sadeghbarati Thanks for the contribution! Could you please tell what the goal of these changes is?

**Comment by sadeghbarati** [comment]
Hi @rokotyan, sorry I didn't explain fully. I apologize 🙌

`useForwardProps` utility is ported from `radix-vue`, and that function is updated, so I thought it would be better to include it here, too

https://github.com/unovue/radix-vue/blob/main/packages/radix-vue/src/shared/useForwardProps.ts

I hope zernonia could clarify whether this change is needed or not

**Comment by zernonia** [comment]
Thanks for the PR @sadeghbarati , however in this particular instance I adapted `useForwardProps` specifically for `unovis`. 
Some component having trouble resolving the complex type, and required to use attribute to pass on the specific props. Thus you can see `const attrs = vm.attrs`.  

I don't think we need to make this changes 😁

**Pull request closed without merging**
